In [1]:
! pip install numpy

In [ ]:
## Creting Array Using NumPy
import numpy as np

# Create a 1D Array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)
print(arr1.reshape(1,5))

arr2 = np.array([[1,2,3,4,5]])
print(arr2.shape)

arr3 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr3.shape)

np.arange(0,10,2)
np.arange(0,10,2).reshape(5,1)



[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
[[1 2 3 4 5]]
(1, 5)
(2, 5)


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
## Some Special Mtrix
np.ones((3,5))
np.zeros((3,5))
np.eye(3)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
## NumPy Vectorise Operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# Element Wise Addition 
print(arr1 + arr2)
# Element Wise Addition 
print(arr1 - arr2)
# Element Wise Addition 
print(arr1 * arr2)
# Element Wise Addition 
print(arr1 / arr2)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


In [29]:
## Universal Functions
arr = np.array([2,3,4,5,6])
# Square Root
print(np.sqrt(arr))
# Expo
print(np.exp(arr))
# Log
print(np.log(arr))
# Sine
print(np.sin(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


In [36]:
### Arrray Sclicing And Indexing

arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
print(arr.shape)

print(arr)
print(arr[0][0])
print(arr[1:,2:])

## Modify Array Elements
arr[0][0] = 100
print(arr)

(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[[ 7  8]
 [11 12]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [ ]:
import numpy as np
## Stastical Concept --Normalization
# To have a mean of 0 and Standard Deviation 1
data = np.array([1,2,3,4])

# Mean
mean = np.mean(data)
print(mean)
# Standard Deviation
std = np.std(data)
print(std)

# Normalize The Data
normalized_data = (mean)/std
print(normalized_data)


2.5
1.118033988749895
2.23606797749979


In [ ]:
## Logical Operations
data = np.array([1,2,3,4,5,6,7,8,9,10])
print(data > 5)
print(data[data > 5])
print(data[(data > 5) & (data <= 8)])
print(data[(data > 5) | (data <= 8)])